---
# Initial version
- hosts: all
  remote_user: root

  # here we make a variable named "env" that is a dictionary
  vars:
    env:
       HI: test2

  tasks:

    # here we just define the dictionary directly and use it
    # (here $HI is the shell variable as nothing in Ansible will replace it)

    - shell: echo $HI
      environment:
         HI: test1

    # here we are using the $env variable above

    - shell: echo $HI
      environment: "{{ env }}"
