---
# Initial version
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - yum: "name={{ item }} state=installed"
      with_items:
        - git
        - wget
        - zip
        - unzip
        - bash
        - mc
